name: Terraform

on:
  push:
    branches:
      - '**'         # all branches
  pull_request:
    branches:
      - main         # PR to main

permissions:
  contents: read
  id-token: write   # for OIDC auth

jobs:

  # ---------------------------
  # PLAN on branch push (NOT main)
  # ---------------------------
  plan-branch:
    if: github.event_name == 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token' # Standard format for most GCP actions
          workload_identity_provider: 'projects/910979016640/locations/global/workloadIdentityPools/iac-github-actions/providers/github-provider'
          service_account: 'wif-for-gitops@project-07b2981c-18fb-4fa4-acd.iam.gserviceaccount.com'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  # ---------------------------
  # PLAN on PR to main
  # ---------------------------
  plan-pr:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token' # Standard format for most GCP actions
          workload_identity_provider: 'projects/910979016640/locations/global/workloadIdentityPools/iac-github-actions/providers/github-provider'
          service_account: 'wif-for-gitops@project-07b2981c-18fb-4fa4-acd.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  # ---------------------------
  # APPLY after merge to main
  # ---------------------------
  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment: production   # 👈 approval gate

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve


#gcloud iam service-accounts add-iam-policy-binding "wif-for-gitops@project-07b2981c-18fb-4fa4-acd.iam.gserviceaccount.com" \
 #   --project="project-07b2981c-18fb-4fa4-acd" \
  #  --role="roles/iam.workloadIdentityUser" \
   # --member="principalSet://iam.googleapis.com/projects/910979016640/locations/global/workloadIdentityPools/iac-github-actions/attribute.repository/Swaroop-751/gitops-terraform"
    #https://iam.googleapis.com/projects/910979016640/locations/global/workloadIdentityPools/iac-github-actions/providers/github