name: Trigger Remote Workflow
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_B_TOKEN }}" \
            https://api.github.com/repos/Swaroop-751/E-Commerce-DevOps-Project/dispatches \
            -d '{
              "event_type": "terraform_apply",
              "client_payload": {
                "environment": "dev",
                "triggered_by": "'"${{ github.actor }}"'"
              }
            }'
